require 'user'
require 'role'
require 'team_name'
require 'hall_of_names'
require 'fantasy_fact'
require 'dispute'
require 'fantasy_record'
require 'season'
require 'result'
require 'baseball_result'
require 'football_result'
require 'poll'
require 'question'
require 'response'
require 'answer'

MongoMapper.connection = Mongo::Connection.new('localhost')
MongoMapper.database = 'test_database'